//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerlinORM.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorModules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorModules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MerlinORM.Client.ErrorModules", typeof(ErrorModules).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Manager.
        /// </summary>
        public static string CFG {
            get {
                return ResourceManager.GetString("CFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Conversion Engine.
        /// </summary>
        public static string CVT {
            get {
                return ResourceManager.GetString("CVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database System.
        /// </summary>
        public static string DBM {
            get {
                return ResourceManager.GetString("DBM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Mapping System.
        /// </summary>
        public static string MAP {
            get {
                return ResourceManager.GetString("MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Engine Pipeline.
        /// </summary>
        public static string QEP {
            get {
                return ResourceManager.GetString("QEP", resourceCulture);
            }
        }
    }
}
